//
//  LocalMacro.h
//  AgentSsales
//
//  Created by innofive on 17/3/23.
//  Copyright © 2017年 英诺. All rights reserved.
//

#ifndef LocalMacro_h
#define LocalMacro_h


#define LocalLogin kLocalizedString(@"login", @"登录")
#define LocalLanguage kLocalizedString(@"language", @"语言")
#define LocalLanguageSeting kLocalizedString(@"langSeting", @"正在设置语言,请稍后...")
#define LocalChinese kLocalizedString(@"chinese", @"中文")
#define LocalMalay kLocalizedString(@"malay", @"马来语")
#define LocalEnglish kLocalizedString(@"english", @"英语")
#define LocalUserID kLocalizedString(@"userID", @"账号")
#define LocalInputID kLocalizedString(@"inputID", @"输入注册手机号")
#define LocalUserPwd kLocalizedString(@"userPwd", @"密码")
#define LocalInputPwd kLocalizedString(@"inputPwd", @"输入登录密码")
#define LocalRememberPwd kLocalizedString(@"rememberPwd", @"记住密码")
#define LocalFogetPwd kLocalizedString(@"fogetPwd", @"忘记密码")
#define LocalVisterIn kLocalizedString(@"visterIn", @"使用游客登录")
#define LocalRegister kLocalizedString(@"register", @"注册")
#define LocalCountry kLocalizedString(@"country", @"国家")
#define LocalCountryID kLocalizedString(@"countryID", @"选择您所在的国家")
#define LocalPhoneID kLocalizedString(@"phoneID", @"手机号")
#define LocalCodeID kLocalizedString(@"codeID", @"验证码")
#define LocalInputCodeID kLocalizedString(@"inputCodeID", @"输入验证码")
#define LocalReadOK kLocalizedString(@"readOK", @"我已阅读并同意")
#define LocalAgreement kLocalizedString(@"agreement", @"用户协议")
#define LocalSendCodeID kLocalizedString(@"sendCodeID", @"发送验证码")
#define LocalCodeLast kLocalizedString(@"codeLast", @"已发送")
#define LocalNext kLocalizedString(@"next", @"下一步")
#define LocalNewPwd kLocalizedString(@"newPwd", @"新密码")
#define LocalInputNewPwd kLocalizedString(@"inputNewPwd", @"请输入新密码，6-20位数")
#define LocalConfirmPwd kLocalizedString(@"confirmPwd", @"确认密码")
#define LocalAgainPwd kLocalizedString(@"againInputPwd", @"再次输入密码")
#define LocalConfirmChange kLocalizedString(@"confirmChange", @"确认修改")

#define LocalHome kLocalizedString(@"home", @"首页")
#define LocalSearchContent kLocalizedString(@"searchContent", @"请输入搜索内容")
#define LocalPurchasePlatform kLocalizedString(@"purchasePlatform", @"代购平台")
#define LocalExchangeRate kLocalizedString(@"exchangeRate", @"实时汇率")
#define LocalSpecialPurchase kLocalizedString(@"specialPurchase", @"惠色特购")
#define LocalHotClasses kLocalizedString(@"hotClasses", @"热门分类")
#define LocalMore kLocalizedString(@"more", @"更多")
#define LocalHot kLocalizedString(@"hot", @"热")
#define LocalGoodsDetail kLocalizedString(@"goodsDetail", @"商品详情")
#define LocalImageDetail kLocalizedString(@"imageDetail", @"图文详情")
#define LocalGoodsPara kLocalizedString(@"goodsPara", @"商品参数")
#define LocalJoinCart kLocalizedString(@"joinCart", @"加入购物车")
#define LocalNowBuy kLocalizedString(@"nowBuy", @"立即购买")
#define LocalSelect kLocalizedString(@"select", @"选择")
#define LocalSelectNum kLocalizedString(@"selectNum", @"选择数量")

#define LocalSearch kLocalizedString(@"search", @"搜索")
#define LocalSearchHistory kLocalizedString(@"searchHistory", @"搜索历史")
#define LocalNoSearchTips kLocalizedString(@"noSearchTips", @"暂无搜索内容")


#define LocalNews kLocalizedString(@"news", @"资讯")
#define LocalNewsCenter kLocalizedString(@"newsCenter", @"资讯中心")
#define LocalNewsDetail kLocalizedString(@"newsDetail", @"资讯详情")
#define LocalComment kLocalizedString(@"comment", @"评论")
#define LocalSayThing kLocalizedString(@"sayThing", @"说点什么吧")
#define LocalPublish kLocalizedString(@"publish", @"发布")

#define LocalShopCart kLocalizedString(@"shopCart", @"购物车")
#define LocalAllSelect kLocalizedString(@"allSelect", @"全选")
#define LocalCancel kLocalizedString(@"cancel", @"取消")
#define LocalPurGoods kLocalizedString(@"purchasingGoods", @"代购商品")
#define LocalPlaGoods kLocalizedString(@"platformGoods", @"平台商品")
#define LocalCartNoGoods kLocalizedString(@"cartNoGoods", @"当前购物车没有商品")
#define LocalEdit kLocalizedString(@"edit", @"编辑")
#define LocalStock kLocalizedString(@"stock", @"库存不足")
#define LocalShelf kLocalizedString(@"shelf", @"已下架")
#define LocalNothing kLocalizedString(@"nothing", @"暂无")
#define LocalTotalCost kLocalizedString(@"totalCost", @"总计(不含邮费)")
#define LocalBalance kLocalizedString(@"balance", @"结算")

#define LocalPerfectInfor kLocalizedString(@"perfectInfor", @"完善个人资料")
#define LocalPerfectTips kLocalizedString(@"perfectTips", @"需要完善个人资料才能购买哦~")
#define LocalGoPerfect kLocalizedString(@"goPerfect", @"去完善")
#define LocalRecName kLocalizedString(@"recName", @"姓名")
#define LocalInputRecName kLocalizedString(@"inputRecName", @"请输入收货人的姓名")
#define LocalRecPhone kLocalizedString(@"recPhone", @"手机号码")
#define LocalInputRecPhone kLocalizedString(@"inputRecPhone", @"请输入收货人的手机号码")
#define LocalArea kLocalizedString(@"area", @"所在地区")
#define LocalSelectArea kLocalizedString(@"selectArea", @"请选择所在地区")
#define LocalDetailArea kLocalizedString(@"detailArea", @"详细地址")
#define LocalInputDeatilArea kLocalizedString(@"inputDeatilArea", @"请输入详细地址")
#define LocalEmail kLocalizedString(@"email", @"邮箱")
#define LocalInputEmail kLocalizedString(@"inputEmail", @"请输入邮箱地址")
#define LocalCardID kLocalizedString(@"cardID", @"身份证")
#define LocalInputCardID kLocalizedString(@"inputCardID", @"请输入身份证号码（选填）")
#define LocalSave kLocalizedString(@"save", @"保存")

#define LocalFirmOrder kLocalizedString(@"firmOrder", @"确认订单")
#define LocalPostWay kLocalizedString(@"postWay", @"配送方式")
#define LocalPleaseSelect kLocalizedString(@"pleaseSelect", @"请选择")
#define LocalChineseMoney kLocalizedString(@"chineseMoney", @"人民币")
#define LocalMalayMoney kLocalizedString(@"malayMoney", @"马来西亚币")
#define LocalAmericanMoney kLocalizedString(@"americanMoney", @"美元")
#define LocalMoneyType kLocalizedString(@"moneyType", @"元")
#define LocalMoneyMark kLocalizedString(@"moneyMark", @"￥")
#define LocalYuan kLocalizedString(@"yuan", @"元")
#define LocalDollar kLocalizedString(@"dollar", @"美元")
#define LocalRinggit kLocalizedString(@"ringgit", @"林吉特")
#define LocalGoodsTotal kLocalizedString(@"goodsTotal", @"件商品，共计")
#define LocalPostMoney kLocalizedString(@"postMoney", @"邮费")
#define LocalCouponDeduction kLocalizedString(@"couponDeduction", @"优惠券抵扣")
#define LocalSelectCoupon kLocalizedString(@"selectCoupon", @"选择我的优惠券")
#define LocalNotSupportTips kLocalizedString(@"notSupportTips", @"代购商品不支持")
#define LocalPriceTotal kLocalizedString(@"priceTotal", @"应付总额")
#define LocalSubmitOrder kLocalizedString(@"submitOrder", @"提交订单")
#define LocalPayMoney kLocalizedString(@"payMoney", @"付款")
#define LocalPayPostage kLocalizedString(@"payPostage", @"付邮费")
#define LocalOrderInfor kLocalizedString(@"orderInfor", @"订单信息")
#define LocalPayWay kLocalizedString(@"payWay", @"支付方式")
#define LocalAlipay kLocalizedString(@"alipay", @"支付宝")
#define LocalWeichat kLocalizedString(@"weichat", @"微信")
#define LocalBankcard kLocalizedString(@"bankcard", @"借记卡/信用卡")
#define LocalNoSupport kLocalizedString(@"noSupport", @"暂不支持")
#define LocalFinishPay kLocalizedString(@"finishPay", @"完成付款")
#define LocalPaySuccess kLocalizedString(@"paySuccess", @"支付成功")
#define LocalCongratulations kLocalizedString(@"congratulations", @"恭喜你")
#define LocalDeliverGoods kLocalizedString(@"deliverGoods", @"送货信息")
#define LocalDeliverTips kLocalizedString(@"deliverTips", @"我们将尽快安排发货...")
#define LocalBackPage kLocalizedString(@"backPage", @"返回首页")
#define LocalCheckOrder kLocalizedString(@"checkOrder", @"查看订单")

#define LocalMine kLocalizedString(@"mine", @"我的")
#define LocalAccountLast kLocalizedString(@"accountLast", @"账户余额:")
#define LocalAllOrder kLocalizedString(@"allOrder", @"全部订单")
#define LocalWaitHandle kLocalizedString(@"waitHandle", @"待处理")
#define LocalWaitPay kLocalizedString(@"waitPay", @"待付款")
#define LocalWaitPPay kLocalizedString(@"waitPPay", @"待付邮费")
#define LocalWaitSend kLocalizedString(@"waitSend", @"待发货")
#define LocalWaitReceive kLocalizedString(@"waitReceive", @"待收货")
#define LocalCompleted kLocalizedString(@"completed", @"已完成")

#define LocalMyOrder kLocalizedString(@"myOrder", @"我的订单")
#define LocalNoOrderTisp kLocalizedString(@"noOrderTisp", @"当前没有订单信息")
#define LocalCancelOrder kLocalizedString(@"cancelOrder", @"取消订单")
#define LocalPayment kLocalizedString(@"payment", @"马上付款")
#define LocalWhyNotPay kLocalizedString(@"whyNotPay", @"为何不能马上付款？")
#define LocalPrompt kLocalizedString(@"prompt", @"提醒发货")
#define LocalViewLogistics kLocalizedString(@"viewLogistics", @"查看物流")
#define LocalConReceipt kLocalizedString(@"conReceipt", @"确认收货")
#define LocalAnotherOne kLocalizedString(@"anotherOne", @"再来一单")
#define LocalOrderDetails kLocalizedString(@"orderDetails", @"订单详情")
#define LocalConsignee kLocalizedString(@"consignee", @"收货人信息")
#define LocalGoodsInfor kLocalizedString(@"goodsInfor", @"商品信息")
#define LocalNoLogisticsTips kLocalizedString(@"noLogisticsTips", @"当前没有物流信息")
#define LocalLogisticsInfor kLocalizedString(@"logisticsInfor", @"物流信息")
#define LocalOrderNumber kLocalizedString(@"orderNumber", @"订单编号")
#define LocalOrderTime kLocalizedString(@"orderTime", @"下单时间")
#define LocalPayTime kLocalizedString(@"payTime", @"付款时间")
#define LocalPostAddress kLocalizedString(@"postAddress", @"发货地址")
#define LocalOrderStatus kLocalizedString(@"orderStatus", @"订单状态")

#define LocalMyCollection kLocalizedString(@"myCollection", @"我的收藏")
#define LocalInvalid kLocalizedString(@"invalid", @"已失效")
#define LocalDelete kLocalizedString(@"delete", @"删除")
#define LocalSelectAll kLocalizedString(@"selectAll", @"全选")
#define LocalDone kLocalizedString(@"done", @"完成")

#define LocalMyDistribution kLocalizedString(@"myDistribution", @"我的分销")

#define LocalRegular kLocalizedString(@"regular", @"规则")
#define LocalTotalCommiss kLocalizedString(@"totalCommiss", @"佣金总额")
#define LocalHistCommiss kLocalizedString(@"histCommiss", @"历史佣金")
#define LocalMyFans kLocalizedString(@"myFans", @"我的粉丝")
#define LocalPeople kLocalizedString(@"people", @"人")
#define LocalTime kLocalizedString(@"time", @"时间")
#define LocalSource kLocalizedString(@"source", @"来源")
#define LocalCommission kLocalizedString(@"commission", @"佣金")

#define LocalMyWallet kLocalizedString(@"myWallet", @"我的钱包")
#define LocalExchangeRate kLocalizedString(@"exchangeRate", @"实时汇率")
#define LocalBuyIn kLocalizedString(@"buyIn", @"买进")
#define LocalSellOut kLocalizedString(@"sellOut", @"卖出")
#define LocalRecharge kLocalizedString(@"recharge", @"充值")
#define LocalWalletRecharge kLocalizedString(@"walletRecharge", @"钱包充值")
#define LocalNote kLocalizedString(@"note", @"说明")
#define LocalAccount kLocalizedString(@"account", @"账户")
#define LocalInputMoney kLocalizedString(@"inputMoney", @"请输入金额")
#define LocalCompleteRecharge kLocalizedString(@"completeRecharge", @"完成充值")
#define LocalRechargeSuccess kLocalizedString(@"rechargeSuccess", @"充值成功")
#define LocalMoneyChanging kLocalizedString(@"moneyChanging", @"兑换货币")
#define LocalCurrencyExchange kLocalizedString(@"currencyExchange", @"货币兑换")
#define LocalHoldCurrency kLocalizedString(@"holdCurrency", @"持有货币")
#define LocalCurrentLast kLocalizedString(@"currentLast", @"当前余额为")
#define LocalFullConver kLocalizedString(@"fullConver", @"全部兑换")

#define LocalMyCoupon kLocalizedString(@"myCoupon", @"我的优惠券")
#define LocalAddressManager kLocalizedString(@"addressManagement", @"收货地址管理")
#define LocalNoAddressTips kLocalizedString(@"noAddressTips", @"暂无收货地址")
#define LocalMyTwoCode kLocalizedString(@"myTwoCode", @"我的二维码")
#define LocalSettings kLocalizedString(@"settings", @"设置")

#define LocalWorkability kLocalizedString(@"workability", @"可使用")

#define LocalNoCouponTisp kLocalizedString(@"noCouponTisp", @"当前没有优惠券信息")

#define LocalNewOne kLocalizedString(@"newOne", @"新建")
#define LocalNewAddress kLocalizedString(@"newAddress", @"新增收货地址")
#define LocalChangeAddress kLocalizedString(@"changeAddress", @"修改收货地址")
#define LocalDefaultAddress kLocalizedString(@"defaultAddress", @"设为默认地址")
#define LocalShare kLocalizedString(@"share", @"分享")
#define LocalShareCode kLocalizedString(@"shareCode", @"分享我的二维码")
#define LocalSharetips kLocalizedString(@"shareTips", @"让朋友扫一扫,即可成为我的粉丝")

#define LocalPushSwitch kLocalizedString(@"pushSwitch", @"推送开关")
#define LocalClearCache kLocalizedString(@"clearCache", @"清除缓存")
#define LocalSuggestions kLocalizedString(@"suggestions", @"意见反馈")
#define LocalSuggestTips kLocalizedString(@"suggestTips", @"有意见或建议都可以写一下哦~")
#define LocalSubmit kLocalizedString(@"submit", @"提交")
#define LocalCommonQuestions kLocalizedString(@"commonQuestions", @"常见问题")
#define LocalDistributionRules kLocalizedString(@"distributionRules", @"分销规则")
#define LocalExchangeNote kLocalizedString(@"exchangeNote", @"兑换说明")
#define LocalRechargeInstructions kLocalizedString(@"rechargeInstructions", @"充值说明")

#define LocalContactSerVice kLocalizedString(@"contactSerVice", @"联系客服")
#define LocalExit kLocalizedString(@"exit", @"退出登录")

#define LocalInforChange kLocalizedString(@"inforChange", @"个人资料修改")
#define LocalHeadImg kLocalizedString(@"headImg", @"头像")
#define LocalNickName kLocalizedString(@"nickName", @"昵称")
#define LocalAccountSafe kLocalizedString(@"accountSafe", @"账号安全")
#define LocalChangePwd kLocalizedString(@"changePwd", @"密码修改")
#define LocalChangePhone kLocalizedString(@"changePhone", @"修改手机")
#define LocalNewPhone kLocalizedString(@"newPhone", @"新号码")
#define LocalInputNewPhone kLocalizedString(@"inputNewPhone", @"请输入新号码")
#define LocalOldPwd kLocalizedString(@"oldPwd", @"旧密码")
#define LocalInputOldPwd kLocalizedString(@"inputOldPwd", @"请输入旧密码")

#define LocalSelectYouCountry kLocalizedString(@"selectYouCountry", @"选择国")
#define LocalSelectYouProvinces kLocalizedString(@"selectYouProvinces", @"选择省")
#define LocalSelectYouCity kLocalizedString(@"selectYouCity", @"选择市")
#define LocalSelectYouArea kLocalizedString(@"selectYouArea", @"选择区")

#define LocalLoading kLocalizedString(@"loading", @"加载中...")
#define LocalInputIsEmpty kLocalizedString(@"inputIsEmpty", @"输入不能为空")
#define LocalCCodeError kLocalizedString(@"cCodeError", @"验证码输入错误")
#define LocalInputIsError kLocalizedString(@"inputIsError", @"输入有误，请重新输入")
#define LocalUserNameIsError kLocalizedString(@"userNameIsError", @"账号或密码输入有误")
#define LocalSelectGoods kLocalizedString(@"selectGoods", @"请选择商品")
#define LocalChangeSuccess kLocalizedString(@"changeSuccess", @"修改成功")
#define LocalChangeFailure kLocalizedString(@"changeFailure", @"修改失败")
#define LocalDelectSuccess kLocalizedString(@"delectSuccess", @"删除成功")
#define LocalDelectFailure kLocalizedString(@"delectFailure", @"删除失败")
#define LocalLikeSuccess kLocalizedString(@"likeSuccess", @"点赞成功")
#define LocalLikeFailure kLocalizedString(@"likeFailure", @"你已经点过赞，不能再点了")
#define LocalAddSuccess kLocalizedString(@"addSuccess", @"添加成功")
#define LocalAddFailure kLocalizedString(@"addFailure", @"添加失败")
#define LocalSaveSuccess kLocalizedString(@"saveSuccess", @"保存成功")
#define LocalSaveFailure kLocalizedString(@"saveFailure", @"保存失败")
#define LocalCommentSuccess kLocalizedString(@"commentSuccess", @"评论成功")
#define LocalCommentFailure kLocalizedString(@"commentFailure", @"评论失败")
#define LocalSubmitSuccess kLocalizedString(@"submitSuccess", @"提交成功")
#define LocalSubmitFailure kLocalizedString(@"submitFailure", @"提交失败")
#define LocalSetSuccess kLocalizedString(@"setSuccess", @"设置成功")
#define LocalSetFailure kLocalizedString(@"setFailure", @"设置失败")
#define LocalPaySuccess kLocalizedString(@"paySuccess", @"支付成功")
#define LocalPayFailure kLocalizedString(@"payFailure", @"支付失败")
#define LocalRegisterSuccess kLocalizedString(@"registerSuccess", @"注册成功")
#define LocalRegisterFailure kLocalizedString(@"registerFailure", @"注册失败")
#define LocalLowStocks kLocalizedString(@"lowStocks", @"库存不足")
#define LocalSaveFirst kLocalizedString(@"saveFirst", @"请先保存")
#define LocalAppUnInstall kLocalizedString(@"appUnInstall", @"此设备未安装相应App")
#define LocalOldPwdError kLocalizedString(@"oldPwdError", @"原密码输入错误")
#define LocalPwdDifferent kLocalizedString(@"pwdDifferent", @"两次密码输入不一样")
#define LocalLoadSuccess kLocalizedString(@"loadSuccess", @"加载成功")
#define LocalLoadFailure kLocalizedString(@"loadFailure", @"加载失败")
#define LocalLoadError kLocalizedString(@"loadError", @"未知错误")

/** --------------------------MJRefres-------------------------- */
#define MJRefreshHeaderIdleText kLocalizedString(@"MJRefreshHeaderIdleText", @"下拉可以刷新")
#define MJRefreshHeaderPullingText kLocalizedString(@"MJRefreshHeaderPullingText", @"松开立即刷新")
#define MJRefreshHeaderRefreshingText kLocalizedString(@"MJRefreshHeaderRefreshingText", @"正在刷新数据中...")
#define MJRefreshAutoFooterIdleText kLocalizedString(@"MJRefreshAutoFooterIdleText", @"点击或上拉加载更多")
#define MJRefreshAutoFooterRefreshingText kLocalizedString(@"MJRefreshAutoFooterRefreshingText", @"正在加载更多的数据...")
#define MJRefreshAutoFooterNoMoreDataText kLocalizedString(@"MJRefreshAutoFooterNoMoreDataText", @"已经全部加载完毕")
#define MJRefreshBackFooterIdleText kLocalizedString(@"MJRefreshBackFooterIdleText", @"上拉可以加载更多")
#define MJRefreshBackFooterPullingText kLocalizedString(@"MJRefreshBackFooterPullingText", @"松开立即加载更多")
#define MJRefreshBackFooterRefreshingText kLocalizedString(@"MJRefreshBackFooterRefreshingText", @"正在加载更多的数据...")
#define MJRefreshBackFooterNoMoreDataText kLocalizedString(@"MJRefreshBackFooterNoMoreDataText", @"已经全部加载完毕")
#define MJRefreshHeaderLastTimeText kLocalizedString(@"MJRefreshHeaderLastTimeText", @"最后更新：")

#define MJRefreshHeaderDateTodayText kLocalizedString(@"MJRefreshHeaderDateTodayText", @"今天")
#define MJRefreshHeaderNoneLastDateText kLocalizedString(@"MJRefreshHeaderNoneLastDateText", @"无记录")



#endif /* LocalMacro_h */
